Musica/urls.py
from django.urls import path
from Musica import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='Homepage'),
    path('Register', views.Register, name='Register'),
    path('Login', views.Login, name='Login'),
    path('Logout', views.Logout, name='Logout'),
    path('CheckEmail', views.CheckEmail, name='CheckEmail'),
    path('AddSongs', views.AddSongs.as_view(), name='AddSongs'),
    path('CreatePlaylist', views.CreatePlaylist.as_view(), name='CreatePlaylist'),
    path('Playlists', views.Playlists.as_view(), name='Playlists'),
    path('Songs', views.Songs.as_view(), name='Songs'),
    path('Automate', views.Automate, name='Automate'),
    path('Users', views.Users.as_view(), name='Users'),
    path('Profile/<str:name>', views.Profile.as_view(), name='Profile'),
    path('SinglePlaylist/<str:id>', views.SinglePlaylist.as_view(), name='SinglePlaylist'),
    path('UserPlaylist/<str:id>', views.UserPlaylist.as_view(), name='UserPlaylist'),
    path('RemoveSongFromPlaylist', views.RemoveSongFromPlaylist, name='RemoveSongFromPlaylist'),
    path('AddToPlaylist', views.AddToPlaylist, name='AddToPlaylist'),
    path('CheckLoginPassword', views.CheckLoginPassword, name='CheckLoginPassword'),
    path('GiveDetails', views.GiveDetails, name='GiveDetails'),
    path('DeletePlaylist', views.DeletePlaylist, name='DeletePlaylist'),
    path('MakePrivate', views.MakePrivate, name='MakePrivate'),
    path('CopyTo', views.CopyTo, name='CopyTo'),
]

MusicaProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from Musica import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('MusicaAPI/Song/', views.SongList.as_view()),
                  path('MusicaAPI/Playlist/', views.PlaylistList.as_view()),
                  path('MusicaAPI/Playlist/<str:id>', views.ParticularPlaylistList.as_view()),
                  path('MusicaAPI/Song/<str:id>', views.ParticularSongList.as_view()),
                  path('Musica/', include('Musica.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

Musica/models.py
from django.db import models
from django.contrib.auth.models import auth, User


class Song(models.Model):
    Name = models.CharField(max_length=9999)
    Album = models.CharField(max_length=9999)
    Artist = models.CharField(max_length=9999)
    Year = models.CharField(max_length=10)
    Song_File = models.FileField()
    Album_Art = models.CharField(max_length=1000000, default='', blank=True)

    def __str__(self):
        return self.Name


class Playlist(models.Model):
    Playlist_Owner = models.ForeignKey(User, on_delete=models.CASCADE)
    Playlist_Name = models.CharField(max_length=999)
    Songs_In_Playlist = models.ManyToManyField(Song, blank=True)
    Visibility = models.CharField(max_length=100)
    Public = models.BooleanField(default=False)

    def __str__(self):
        return self.Playlist_Name + 'by' + self.Playlist_Owner.first_name

templates/AddSongs.html
{% extends "Base.html" %}
{% load static %}
{% block title %}
    | Add Songs
{% endblock %}
{% block body_block %}

<style>
        .Form {
            width: 40%;
            background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4));
            display: block;
            color: white;
            margin: 50px auto auto;
            padding: 12px 12px 30px;
            position: relative;
            border-radius: 12px;
            box-shadow: 0 0 20px #f5a742;
        }

        .form{
            margin-top: 40px;
        }
        h3 {
            text-align: center;
        }


        .SPAN {
            margin-left: 40px;
            font-weight: bolder;
        }

        input[type='file'] {
            margin-bottom: 20px;
            margin-top: 10px;
            margin-left: 20px;
            display: none;
        }

        .SongFile {
            margin-bottom: 20px;
            margin-top: 10px;
            margin-left: 40px;
            font-weight: bolder;
        }

        input[type='text'] {
            padding: 12px 12px;
            width: 80%;
            height: 40px;
            border-radius: 5px;
            border: none;
            margin-top: 10px;
            margin-left: 40px;
            margin-bottom: 20px;
            box-shadow: 0 0 10px black;
        }

        .Submit {
            display: block;
            margin: 20px auto;
            border: none;
            outline: none;
            background-color: black;
            color: white;
            width: 100px;
            height: 40px;
            border-radius: 5px;
            box-shadow: 0 0 5px #6a6161;
            transition: 0.3s ease;
        }

        .Submit:hover {
            transform: scale(1.2);
            background-color: #f5a742;
        }

        @media screen and (max-width: 768px) {
            .Form {
                width: 90%;
                display: block;
                margin: 10px auto auto;
                padding: 12px 12px 30px;
                position: relative;
            }

            .SPAN{
                margin-left: 30px;
            }
            input[type='text']{
                margin-left: 25px;
            }

        }
    </style>
    <div class="container Form">
        <form class="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <span class="SPAN" style="display: block;">Song Name:</span>
            <input type="text" name="SongName" placeholder="Song Name">
            <span class="SPAN" style="display: block;">Album:</span>
            <input type="text" name="Album" placeholder="Album">
            <span class="SPAN" style="display: block;">Artist:</span>
            <input type="text" name="Artist" placeholder="Artist">
            <span class="SPAN" style="display: block;">Year of Release:</span>
            <input type="text" name="Year" placeholder="Year">
            <span class="SPAN" style="display: block;">Song File:</span>
            <label for="file" class="SongFile">Click here to select a song.</label>
            <input id="file" class="file" type="file" name="File"><br>
            <button class="Submit">Submit</button>
        </form>
    </div>


{% endblock %}

templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Musica {% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/Icon.jpg' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet'/>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/starter-template/">
    <link href='https://fonts.googleapis.com/css?family=Berkshire Swash' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
    body {
        background-color: #2D4B8B;
    }

    .navbar {
        background-color: #0e1a31;
    }

    .navbar-brand {
        font-size: 40px;
        margin-left: 40px;
    }

    .home {
        margin-left: 400px;
    }

    .logout {
        margin-left: 500px;
    }

    .Register {
        margin-left: 1150px;
    }

    .dropdown-item:hover {
        background-color: #FCA311;
    }

    @media screen and (max-width: 1024px) {
        .nav-link {
            border-bottom: 1px solid white;
        }

        .home {
            margin-left: 0;
        }

        .logout {
            margin-left: 0;
            border-bottom: none;
        }

        .Register {
            margin-left: 0px;
            border-bottom: 1px solid white;
        }
    }
</style>

<body>

<nav class="navbar navbar-expand-lg navbar-light">
    <a style="color: white;" class="navbar-brand" href="{% url 'Homepage' %}">Musica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a style="color: white;" class="nav-link home" href="{% url 'Homepage' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a style="color: white;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Features
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'AddSongs' %}">Add Songs</a>
                        <a class="dropdown-item" href="{% url 'CreatePlaylist' %}">Create Playlist</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'Playlists' %}">Modify Playlists</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'Songs' %}">Songs</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'Playlists' %}">Playlists</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'Users' %}">Users</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link logout" href="{% url 'Logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a data-toggle="modal" data-target="#RegisterModal" style="color: white;" class="nav-link Register"
                       href="{% url 'Register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a data-toggle="modal" data-target="#LoginModal" style="color: white; border-bottom: none;"
                       class="nav-link" href="{% url 'Login' %}">Login</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>

{% block body_block %}
{% endblock %}
</body>
</html>

templates/CreatePlaylist.html
{% extends "Base.html" %}
{% load static %}
{% load CustomTemplates %}
{% block title %}
    | Create Playlist
{% endblock %}
{% block body_block %}
    <style>
        .Playlist {
            width: 40%;
            background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4));
            display: block;
            color: white;
            margin: 50px auto auto;
            padding: 12px 12px 30px;
            position: relative;
            border-radius: 12px;
            box-shadow: 0 0 20px #f5a742;
        }

        .INPUT {
            padding: 12px 12px;
            width: 70%;
            height: 40px;
            border-radius: 5px;
            border: none;
            margin-top: 10px;
            margin-left: 40px;
            margin-bottom: 20px;
            box-shadow: 0 0 10px black;
        }

        .Create {
            display: block;
            margin: 20px auto;
            border: none;
            outline: none;
            background-color: black;
            color: white;
            width: 120px;
            height: 40px;
            border-radius: 5px;
            box-shadow: 0 0 5px #6a6161;
            transition: 0.3s ease;
        }

        .Create:hover {
            transform: scale(1.2);
            background-color: #f5a742;
        }

        @media screen and (max-width: 768px) {
            .Playlist {
                width: 90%;
                display: block;
                margin: 50px auto auto;
                padding: 12px 12px 30px;
                position: relative;
            }
        }

        .Each {
            width: 97%;
            height: auto;
            position: relative;
            left: -10px;
            display: inline-block;
        }

        .AlbumArt {
            width: 40px;
            height: 40px;
            position: relative;
            top: 10px;
            left: 20px;
        }

        .SongName {
            font-size: 15px;
            position: relative;
            top: -40px;
            left: 90px;
            max-width: 60%;
            word-break: break-word;
        }

        .MetaData {
            position: relative;
            left: 90px;
            top: -40px;
            max-width: 60%;
            word-break: break-word;
            font-weight: lighter;
        }

        .CHECK {
            position: absolute;
            right: -10px;
            top: 20px;
            height: 15px;
            width: 15px;
            border-radius: 50%;
        }
    </style>
    <div class="container Playlist">
        <h3 style="margin-top: 20px; text-align: center;">Create your own Playlist Here</h3>
        <form action="" method="post">
            {% csrf_token %}
            <span style="display: block; text-align: left; margin-top: 40px; margin-left: 40px; text-decoration: white underline; font-weight: bolder;">Name of your Playlist:</span>
            <input class="INPUT" type="text" name="Name" placeholder="Playlist Name" required>
            <span style="display: block; text-align: left; margin-left: 40px; margin-bottom: 20px; text-decoration: white underline; font-weight: bolder;">Select the Songs:</span>

            {% for i in Songs %}
                <div class="Each">
                    <div class="AlbumArt">
                        <img src="{{ i.Album_Art }}" width="100%"
                             height="100%">
                    </div>
                    <div class="SongName">{{ i.Name }}</div>
                    <div class="MetaData">{{ i.Album }} - {{ i.Artist }} <br> {{ i.Year }}</div>
                    <input class="CHECK" type="checkbox" id="Song_{{ i.id }}" name="{{ i.id }}">
                </div>
            {% endfor %}
            <br>
            <button type="submit" class="Create">Create Playlist</button>
        </form>
    </div>
{% endblock %}

templates/Home.html
{% extends "Base.html" %}
{% load static %}
{% block title %}
    | Home
{% endblock %}
{% block body_block %}

    <style>

        .modal {
            background-color: #14213D;
        }

        .modal-body {
            text-align: center;
        }

        .SPAN {
            display: block;

        }

        input {
            margin-top: 10px;
            margin-bottom: 10px;
            display: block;
        }

        .submit {
            color: white;
            border-radius: 5px;
            width: 100px;
            height: 40px;
            box-shadow: 0 0 5px #6a6161;
            border: none;
            outline: none;
            background-color: black;
            transition: 0.3s ease;
        }

        .submit:hover {
            background-color: #FCA311;
        }

        .HomeImage {
            margin-left: 200px;
            margin-top: -80px;
            width: 60%;
            height: 400px;

        }

        .jumbotron {
            background-color: #f8bd5c;
        }

        .BUTTON1 {
            display: none;
            margin-right: 20px;
            border: none;
            outline: none;
            background-color: black;
            color: white;
            width: 100px;
            height: 40px;
            border-radius: 5px;
            box-shadow: 0 0 5px #6a6161;
            transition: 0.3s ease;
        }

        .BUTTON1:hover {
            transform: scale(1.2);
            background-color: #14213D;
        }

        .BUTTON2 {
            display: none;
            border: none;
            outline: none;
            background-color: black;
            color: white;
            width: 100px;
            height: 40px;
            border-radius: 5px;
            box-shadow: 0 0 5px #6a6161;
            transition: 0.3s ease;
        }

        .BUTTON2:hover {
            transform: scale(1.2);
            background-color: #14213D;
        }


        @media screen and (max-width: 768px) {
            .HomeImage {
                width: 80%;
                height: 200px;
                margin-left: 25px;
                margin-top: -40px;
            }

            .jumbotron {
                width: 80%;
            }

            .BUTTON1 {
                margin-right: 5px;
                display: initial;
            }

            .BUTTON2 {
                display: initial;
            }
        }

    </style>


    <div class="container jumbotron">
        <img class="HomeImage" src="{% static 'img/HomeIcon.png' %}">
        <h3>Musica</h3>
        <p>
            A web application made on django backend app and rest api which can feed data to a music app.
            Musica has a number of features like, to Add Songs, to Create Your Playlist, to Modify your Playlist.
            It also shows the number of users of this Web application and their playlists which may be Private or
            Public.
            To explore the application, Please Register yourself and then Login.
            Thankyou.
        </p>
        {% if not user.is_authenticated %}
            <button data-toggle="modal" data-target="#RegisterModal" class="BUTTON1">Register</button>
            <button data-toggle="modal" data-target="#LoginModal" class="BUTTON2">Login</button>
        {% endif %}
    </div>

    <div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register Yourself to Musica</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
                            id="CloseButtonRegister">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="SPAN">Enter Your Name:</span>
                    <input id="Name" name="Name" class="form-control" type="text" placeholder="Enter Name" required>
                    <span>Enter Your Email:</span>
                    <input id="Email" onkeyup="CheckEmail(this.value);" class="form-control" name="Email" type="email"
                           placeholder="Enter Email" required>
                    <span>Enter Password:</span>
                    <input id="Password1" onkeyup="CheckPassLength(this.value);" class="form-control" name="Password"
                           type="password"
                           placeholder="Enter Password" required>
                    <span>Re-enter Password:</span>
                    <input id="Password2" onkeyup="CheckPassword();" class="form-control" type="password"
                           placeholder="Re-enter Password" required>
                    <div class="modal-footer">
                        <button onclick="Register();" id="RegisterBTN" type="button" class="submit">Register
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register Yourself to Musica</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'Login' %}" method="post" onsubmit="return CheckLoginPassword();">
                        {% csrf_token %}
                        <span>Enter Your Email:</span>
                        <input onkeyup="CheckLoginMail(this.value);" id="LoginMail" class="form-control" name="Email"
                               type="email" placeholder="Enter Email">
                        <span>Enter Password:</span>
                        <input class="form-control" name="Password" id="LoginPassword" type="password"
                               placeholder="Enter Password">
                        <div class="modal-footer">
                            <button type="submit" class="submit">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script>
        function CheckLoginPassword() {
            var res = 0;
            var Email = document.getElementById('LoginMail').value
            var Password = document.getElementById('LoginPassword').value
            $.ajax(
                {
                    type: "POST",
                    url: "{% url 'CheckLoginPassword' %}",
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'Email': Email,
                        'Password': Password,
                    },
                    async: false,
                    dataType: "json",
                    success: function (response) {
                        if (response.Result === 'Done') {
                            res = 1;
                        } else {
                            document.getElementById('LoginPassword').style.border = '2px solid red'
                            res = 0
                        }
                    },
                    error: function (rs) {
                        alert(rs.responseText);
                    }
                });
            return Boolean(res);
        }

        function CheckLoginMail(str) {
            var Email = document.getElementById('LoginMail')
            if (str === '') {

            } else {
                $.ajax(
                    {
                        type: "POST",
                        url: "{% url 'CheckEmail' %}",
                        data: {
                            'csrfmiddlewaretoken': '{{ csrf_token }}',
                            'Email': str,
                        },
                        dataType: "json",
                        success: function (response) {
                            console.log(response)
                            if (response.Result !== 'Not') {
                                Email.style.border = '2px solid lime'
                            } else {
                                Email.style.border = '2px solid red'
                            }
                        },
                        error: function (rs) {
                            alert(rs.responseText);
                        }
                    });
            }
        }

        function CheckEmail(str) {
            var Email = document.getElementById('Email')
            if (str === '') {

            } else {
                $.ajax(
                    {
                        type: "POST",
                        url: "{% url 'CheckEmail' %}",
                        data: {
                            'csrfmiddlewaretoken': '{{ csrf_token }}',
                            'Email': str,
                        },
                        dataType: "json",
                        success: function (response) {
                            console.log(response)
                            if (response.Result === 'Not') {
                                Email.style.border = '2px solid lime'
                            } else {
                                Email.style.border = '2px solid red'
                            }
                        },
                        error: function (rs) {
                            alert(rs.responseText);
                        }
                    });
            }
        }

        function CheckPassword() {
            var a = document.getElementById('Password1').value
            var b = document.getElementById('Password2').value
            if (a === b) {
                document.getElementById('Password2').style.border = '2px solid lime'
            } else {
                document.getElementById('Password2').style.border = '2px solid red'
            }
        }

        function CheckPassLength(str) {
            if (str === '') {
                document.getElementById('Password1').style.border = '2px solid lime'
            } else if (str.length <= 6) {
                document.getElementById('Password1').style.border = '2px solid red'
            } else {
                document.getElementById('Password1').style.border = '2px solid lime'
            }
        }

        function Register() {
            var Name = document.getElementById('Name')
            var Email = document.getElementById('Email')
            var Password1 = document.getElementById('Password1')
            var Password2 = document.getElementById('Password2')
            if (Name.value === '' || Email.value === '' || Password1.value === '' || Password2.value === '') {
                console.log('Error')
            } else {
                $.ajax(
                    {
                        type: "POST",
                        url: "{% url 'Register' %}",
                        data: {
                            'csrfmiddlewaretoken': '{{ csrf_token }}',
                            'Name': Name.value,
                            'Email': Email.value,
                            'Password1': Password1.value,
                        },
                        dataType: "json",
                        success: function (response) {
                            console.log(response)
                            document.getElementById('CloseButtonRegister').click()
                            document.getElementById('OpenButtonLogin').click()
                        },
                        error: function (rs) {
                            alert(rs.responseText);
                        }
                    });
            }
        }

        function CheckAll() {
            var x = document.getElementById('RegisterBTN')
            var Email = document.getElementById('Email').style.border
            var Password1 = document.getElementById('Password1').style.border
            var PAssword2 = document.getElementById('Password2').style.border
            if (Email === '2px solid red' || Password1 === '2px solid red' || PAssword2 === '2px solid red') {
                x.disabled = true;
                return false
            }
            x.disabled = true;
            return true
        }
    </script>


{% endblock %}

templates/Profile.html
{% extends "Base.html" %}
{% load static %}
{% block title %}
    | Profile
{% endblock %}
{% block body_block %}

    <style>
        .Profile {
            margin-top: 50px;
            margin-bottom: 20px;
            width: 50%;
            background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4));
            color: white;
            border-radius: 12px;
            padding: 12px 12px 40px;
            box-shadow: 0 0 20px #f5a742;
        }

        .EachProfile {
            border-bottom: 1px solid white;
            margin-top: 20px;
            margin-bottom: 20px;
            padding-bottom: 20px;
        }

        @media screen and (max-width: 768px){
        .Profile{
            width: 90%;
        }
    }
    </style>





    <div class="container Profile">
        <div class="EachProfile">
            <h3>{{ i.first_name }} {{ i.last_name }}</h3>
            {% if i.playlist_set.all|length == 0 %}
                <h6 style="margin-top: 20px;">No Playlists Created by this User</h6>
            {% else %}
                <h6 style="margin-top: 20px;">Playlists Created by {{ i.first_name }}</h6>
            {% endif %}
            <ul>
                {% for j in i.playlist_set.all %}
                    <a style="color: white;" href="{% url 'SinglePlaylist' j.id %}">
                        <li>{{ j }}</li>
                    </a>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}